---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create web directory
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart nginx

- name: Enable Nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

