---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy proxy config
  ansible.builtin.template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify: restart nginx

- name: Enable Nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

