---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ ['net-tools', 'dnsutils', 'wget', 'curl', 'mc', 'rsync'] }}"
    state: present
    update_cache: yes


