---
- name: Configure all hosts
  hosts: all
  become: yes
  roles:
    - setup_vm

- name: Configure proxy server
  hosts: proxy
  become: yes
  roles:
    - proxy_nginx

- name: Configure backend servers
  hosts: backend
  become: yes
  roles:
    - backend_nginx


